export const veo_loading = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
style="margin: auto; background: none; display: block; shape-rendering: auto;" width="50px" height="50px"
viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<g transform="translate(84,50)">
   <g transform="rotate(0)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="1">
           <animateTransform attributeName="transform" type="scale" begin="-0.875s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.875s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(74.04163056034261,74.04163056034261)">
   <g transform="rotate(45)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.875">
           <animateTransform attributeName="transform" type="scale" begin="-0.75s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.75s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(50,84)">
   <g transform="rotate(90)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.75">
           <animateTransform attributeName="transform" type="scale" begin="-0.625s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.625s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(25.958369439657385,74.04163056034261)">
   <g transform="rotate(135)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.625">
           <animateTransform attributeName="transform" type="scale" begin="-0.5s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.5s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(16,50.00000000000001)">
   <g transform="rotate(180)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.5">
           <animateTransform attributeName="transform" type="scale" begin="-0.375s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.375s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(25.95836943965738,25.958369439657385)">
   <g transform="rotate(225)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.375">
           <animateTransform attributeName="transform" type="scale" begin="-0.25s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.25s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(49.99999999999999,16)">
   <g transform="rotate(270)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.25">
           <animateTransform attributeName="transform" type="scale" begin="-0.125s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="-0.125s"></animate>
       </circle>
   </g>
</g>
<g transform="translate(74.04163056034261,25.95836943965738)">
   <g transform="rotate(315)">
       <circle cx="0" cy="0" r="6" fill="#e1e1e1" fill-opacity="0.125">
           <animateTransform attributeName="transform" type="scale" begin="0s" values="1.5 1.5;1 1"
                             keyTimes="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           <animate attributeName="fill-opacity" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                    values="1;0" begin="0s"></animate>
       </circle>
   </g>
</g>
<!-- [ldio] generated by https://loading.io/ --></svg>
`

export const time_loading = `

<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  width="18px" height="18px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<g transform="rotate(0 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.4854111405835542s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(12.413793103448276 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.4323607427055702s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(24.82758620689655 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.379310344827586s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(37.241379310344826 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.326259946949602s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(49.6551724137931 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.273209549071618s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(62.06896551724138 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.2201591511936338s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(74.48275862068965 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.1671087533156497s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(86.89655172413794 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.1140583554376657s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(99.3103448275862 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.0610079575596816s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(111.72413793103448 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-1.0079575596816976s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(124.13793103448276 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.9549071618037135s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(136.55172413793105 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.9018567639257293s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(148.9655172413793 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.8488063660477453s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(161.3793103448276 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.7957559681697612s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(173.79310344827587 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.7427055702917771s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(186.20689655172413 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.689655172413793s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(198.6206896551724 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.636604774535809s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(211.0344827586207 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.5835543766578248s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(223.44827586206895 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.5305039787798408s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(235.86206896551724 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.47745358090185674s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(248.27586206896552 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.42440318302387264s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(260.6896551724138 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.37135278514588854s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(273.1034482758621 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.3183023872679045s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(285.51724137931035 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.2652519893899204s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(297.9310344827586 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.21220159151193632s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(310.3448275862069 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.15915119363395225s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(322.7586206896552 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.10610079575596816s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(335.17241379310343 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="-0.05305039787798408s" repeatCount="indefinite"></animate>
  </rect>
</g><g transform="rotate(347.58620689655174 50 50)">
  <rect x="43" y="8" rx="7" ry="8" width="14" height="16" fill="rgba(255, 255, 255, 0.5733870967741935)">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.5384615384615383s" begin="0s" repeatCount="indefinite"></animate>
  </rect>
</g>
<!-- [ldio] generated by https://loading.io/ --></svg>
`